spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

  jpa:
    show-sql: false

file:
  upload:
    storage-type: s3
    base-url: ${FILE_BASE_URL:https://onepage-product.onrender.com/api/v1}
    local-path: ${FILE_LOCAL_PATH:uploads}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:kudreambuck}
    region: ${AWS_S3_REGION:ap-east-2}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}

logging:
  level:
    com.onepage: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
